name: Publish to Github

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Project
      run:  ./gradlew build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
    - name: Publishit
      run: ./gradlew -PsigningPassword=${{ secrets.ORG_GRADLE_PROJECT_signingPassword }} -PsigningKey=${{ secrets.ORG_GRADLE_PROJECT_signingKey }} -PsignRequired=true -Pgpr.user=Shinigami072 -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
      env:
          ORG_GRADLE_PROJECT_OSSRH_key: ${{ secrets.ORG_GRADLE_PROJECT_OSSRH_key }} # This token is provided by Actions, you do not need to create your own token
          ORG_GRADLE_PROJECT_OSSRH_user: ${{ secrets. ORG_GRADLE_PROJECT_OSSRH_user }} # This token is provided by Actions, you do not need to create your own token
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }} # This token is provided by Actions, you do not need to create your own token
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }} # This token is provided by Actions, you do not need to create your own token


